const i18Obj = {
	en: {
		skills: 'Services',
		portfolio: 'Portfolio',
		video: 'Video',
		price: 'Price',
		contacts: 'Contacts',
		'hero-title': 'tattoo parlor',
		'hero-text':
			'Dare and make your dream come true, create a masterpiece for yourself with a few strokes in cooperation with the professional salon "Flight of the Soul"',
		hire: 'Use the moment',
		'skill-title-1': 'Tattoo',
		'skill-text-1':
			'High-quality tattoos for every taste, it all depends on the flight of your thoughts and dreams (we do not make roses in the form of cabbage)',
		'skill-title-2': 'Eyebrow tattoo',
		'skill-text-2':
			'We will help to give the eyebrows the desired shape and color, make their contours clearer, Mr. Brezhnev himself will envy your eyebrows.',
		'skill-title-3': 'Piercing',
		'skill-text-3':
			'Add jewelry to your body, highlighting its beauty and personality, so that any crow will be seduced by the brilliance of your jewelry.',
		'skill-title-4': 'Tattoo removal',
		'skill-text-4':
			'Our professionals will help you remove any old tattoo, if your rose has turned into a cabbage, our professionals will help you out.',
		tattoos: 'Tattoos',
		eyebrow: 'Eyebrow tattoo',
		piercing: 'Piercing',
		sketches: 'Sketches',
		'price-description-1-span-1': 'Tattooing',
		'price-description-1-span-2': 'Tattoo fix',
		'price-description-1-span-3': 'Tattoo restoration',
		'price-description-1-span-4': 'Eyebrow tattoo',
		'price-description-2-span-1': 'Classic piercing',
		'price-description-2-span-2': 'Ear piercing',
		'price-description-2-span-3': 'Nose piercing',
		'price-description-2-span-4': 'Eyebrow piercing',
		'price-description-sum-1-span-1': 'from 50 $',
		'price-description-sum-1-span-2': 'from 80 $',
		'price-description-sum-1-span-3': 'from 100 $',
		'price-description-sum-1-span-4': 'from 120 $',
		'price-description-sum-2-span-1': 'from 25 $',
		'price-description-sum-2-span-2': 'from 35 $',
		'price-description-sum-2-span-3': 'from 40 $',
		'price-description-sum-2-span-4': 'from 30 $',
		'price-description-sum': 'from',
		order: 'Order service',
		'contact-me': 'Contact us',
		'mail-placeholder': 'Email',
		'tel-placeholder': 'Phone',
		'message-placeholder': 'Message',
		'send-message': 'Send message',
	},
	ru: {
		skills: 'Услуги',
		portfolio: 'Портфолио',
		video: 'Видео',
		price: 'Цены',
		contacts: 'Контакты',
		'hero-title': 'тату-салон',
		'hero-text':
			'Дерзайте и воплощайте свою мечту, создайте шедевр для себя несколькими штрихами в сотрудничестве с профессиональным салоном «Полет души».',
		hire: 'Используй момент',
		'skill-title-1': 'Тату',
		'skill-text-1':
			'Качественные татуировки на любой вкус, все зависит от полета вашей мысли и мечты (мы не делаем розы в виде капусты)',
		'skill-title-2': 'Татуаж бровей',
		'skill-text-2':
			'Мы поможем придать бровям желаемую форму и цвет, сделать их контуры более четкими, вашим бровям позавидует сам господин Брежнев.',
		'skill-title-3': 'Пирсинг',
		'skill-text-3':
			'Добавьте украшения на свое тело, подчеркнув его красоту и индивидуальность, так что любая ворона будет соблазнена блеском ваших украшений.',
		'skill-title-4': 'Удаление татуировки',
		'skill-text-4':
			'Наши профессионалы помогут вам удалить любую старую татуировку, если ваша роза превратилась в капусту, наши профессионалы выручат вас.',
		tattoos: 'Татуировки',
		eyebrow: 'Татуаж бровей',
		piercing: 'Пирсинг',
		sketches: 'Эскизы',
		'price-description-1-span-1': 'Нанесение татуировки',
		'price-description-1-span-2': 'Исправление татуировки',
		'price-description-1-span-3': 'Реставрация татуировок',
		'price-description-1-span-4': 'Татуаж',
		'price-description-2-span-1': 'Классический пирсинг',
		'price-description-2-span-2': 'Пирсинг ушей',
		'price-description-2-span-3': 'Пирсинг носа',
		'price-description-2-span-4': 'Пирсинг брови',
		'price-description-sum-1-span-1': 'от 50 $',
		'price-description-sum-1-span-2': 'от 80 $',
		'price-description-sum-1-span-3': 'от 100 $',
		'price-description-sum-1-span-4': 'от 120 $',
		'price-description-sum-2-span-1': 'от 25 $',
		'price-description-sum-2-span-2': 'от 35 $',
		'price-description-sum-2-span-3': 'от 40 $',
		'price-description-sum-2-span-4': 'от 30 $',
		order: 'Заказать услугу',
		'contact-me': 'Свяжитесь с нами',
		'mail-placeholder': 'Почта',
		'tel-placeholder': 'Номер телефона',
		'message-placeholder': 'Сообщение',
		'send-message': 'Отправить',
	},
}
export default i18Obj
